tmfeedback/clubs/urls.py
from django.urls import path, include

from . import views
from meetings import views as meet_views

meet_urlpatterns = [
    path('', meet_views.MeetingListView.as_view(), name='meeting_index'),
    path('create/', meet_views.MeetingCreateView.as_view(), name='create_meeting'),
]

app_name = 'clubs'
urlpatterns = [
    path('', views.ClubIndexView.as_view(), name='index'),
    path('create/', views.ClubCreateView.as_view(), name='create'),
    path('<int:club_id>/', views.ClubHomeView.as_view(), name='home'),
    path('<int:club_id>/roster/', views.ClubMemberRoster.as_view(), name='member_roster'),
    path('<int:club_id>/membership_requests/', views.ClubManageRequestsView.as_view(), name='membership_requests'),
    path('<int:club_id>/meetings/', include(meet_urlpatterns))
]

tmfeedback/tmfeedback/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from homepage import views
from users import views as users_views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    path('signup/', users_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('about/', views.about, name='about'),
    path('boards/', include('boards.urls')),
    path('clubs/', include('clubs.urls', namespace='clubs')),
    path('meetings/', include('meetings.urls.meetings', namespace='meetings')),
    path('performances/', include('meetings.urls.performances', namespace='performances')),
    path('evals/', include('evaluations.urls', namespace='evals')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

tmfeedback/meetings/models.py
from django.db import models
from django.conf import settings
from datetime import date as dt
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from clubs.models import Club


class Meeting(models.Model):
    date = models.DateField()
    theme = models.CharField(max_length=100)
    club = models.ForeignKey(Club, on_delete=models.CASCADE, related_name='meetings')

    def __str__(self):
        return dt.strftime(self.date, "%b %d, %Y") + ' - ' + self.theme

    def get_absolute_url(self):
        kwargs = {
            'meeting_pk': self.pk
        }
        return reverse('meetings:detail', kwargs=kwargs)


def get_default_user():
    return get_user_model().get_deleted_default_user()


class Performance(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE, related_name='performances')
    performer = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  on_delete=models.SET(get_default_user),
                                  related_name='performances')

    # Performance Roles
    class Role(models.TextChoices):
        TOASTMASTER = 'TMD', _('Toastmaster')
        TABLE_TOPICS_MASTER = 'TTM', _('Table Topics Master')
        EVALUATOR = 'EVAL', _('Evaluator')
        GENERAL_EVALUATOR = 'GE', _('General Evaluator')
        SPEAKER = 'S', _('Speaker')
        TABLE_TOPICS_SPEAKER = 'TTS', _('Table Topics Speaker')

    role = models.CharField(max_length=4, choices=Role.choices, default=Role.SPEAKER)

    def __str__(self):
        return '{date} {role} {user}'.format(date=dt.strftime(self.meeting.date, "%m-%d-%y"),
                                             role=self.get_role_label(),
                                             user=self.performer.first_name)

    def get_role_label(self):
        return self.Role(self.role).label

    def get_absolute_url(self):
        kwargs = {
            'meeting_pk': self.meeting.pk,
            'perf_pk': self.pk
        }
        return reverse('meetings:perf_detail', kwargs=kwargs)

tmfeedback/meetings/forms.py
from django import forms
from django.forms.widgets import SelectDateWidget

from .models import Meeting


class MeetingCreationForm(forms.ModelForm):
    date = forms.DateField(
        widget=SelectDateWidget(
            empty_label=('Choose Month', 'Choose Day', 'Choose Year')
        )
    )

    class Meta:
        model = Meeting
        exclude = ('club',)

tmfeedback/meetings/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, CreateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
import sys

from .models import Meeting, Performance
from .forms import MeetingCreationForm
from clubs.models import Club
from clubs.views import ClubMembershipRequiredMixin, ClubOrganizerRequiredMixin


class MeetingListView(ListView):
    model = Meeting
    paginate_by = 20
    context_object_name = 'meetings'
    template_name = 'meetings/meeting_list.html'

    def get_queryset(self):
        self.club = get_object_or_404(Club, pk=self.kwargs.get('club_id'))
        queryset = self.club.meetings.order_by('-date')
        return queryset

    def get_context_data(self, **kwargs):
        kwargs['club'] = self.club
        return super().get_context_data(**kwargs)


class MeetingDetailView(DetailView):
    template_name = 'meetings/meeting_detail.html'
    context_object_name = 'meeting'

    def get_object(self):
        meeting_pk = self.kwargs.get('meeting_pk')
        return get_object_or_404(Meeting, pk=meeting_pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['club'] = self.object.club
        context['performances'] = self.object.performances.all()
        return context


class MeetingCreateView(LoginRequiredMixin, ClubMembershipRequiredMixin, CreateView):
    template_name = 'meetings/meeting_create.html'
    # TODO: specify a form_class to add extra validation so that clubs can't have multiple meetings with the same date
    form_class = MeetingCreationForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        club_id = self.kwargs.get('club_id')
        self.club = get_object_or_404(Club, id=club_id)
        context['club'] = self.club
        return context

    def form_valid(self, form):
        club_id = self.kwargs.get('club_id')
        self.club = get_object_or_404(Club, id=club_id)
        form.instance.club = self.club
        return super().form_valid(form)


class PerformanceDetailView(DetailView):
    template_name = 'meetings/performance_detail.html'
    context_object_name = 'performance'

    def get_object(self):
        perf_pk = self.kwargs.get('perf_pk')
        return get_object_or_404(Performance, pk=perf_pk)

    def get_context_data(self, **kwargs):
        meeting = self.object.meeting
        context = super().get_context_data(**kwargs)
        context['club'] = meeting.club
        context['meeting'] = meeting
        context['evaluations'] = self.object.evals_received.all()
        return context

tmfeedback/meetings/templates/meetings/meeting_create.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  Create a New Meeting
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'clubs:home' club.id %}">{{club.name}}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'clubs:meeting_index' club.id %}">All Meetings</a></li>
  <li class="breadcrumb-item active">New Meeting</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Create Meeting</button>
  </form>
{% endblock %}

tmfeedback/meetings/templates/meetings/meeting_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  {{meeting}}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'clubs:home' club.id %}">{{club.name}}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'clubs:meeting_index' club.id %}">All Meetings</a></li>
  <li class="breadcrumb-item active">{{meeting}}</li>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="card" style="margin-top:25px">
      <h3 class="card-header text-white bg-dark">Meeting: {{ meeting }}</h3>
      <div class="card-body">
        <p>Date: {{meeting.date}}</p>
        <p>Theme: {{meeting.theme}}</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="card" style="margin-top:25px">
      <h4 class="card-header text-white bg-dark">Performances</h4>
      <div class="card-body">
        <table class="table">
          <thead class="thead-inverse">
            <tr>
              <th>Performer</th>
              <th>Role</th>
              <th>Title</th>
              <th>Evaluations</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            {% for perf in performances %}
              <tr>
                <td><a href="{% url 'performances:detail' perf.pk %}">
                    {{ perf.performer.get_full_name }}
                  </a>
                </td>
                <td>{{ perf.get_role_label }}</td>
                <td>Title</td>
                <td>0</td>
                <td class="align-middle">
                  <a href="{% url 'performances:create_eval' perf.pk %}" class="btn btn-success">Evaluate</a>
                  <a href="#">Edit</a>
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
        <a href="#" class="btn btn-primary" style="margin-top:10px">Add Performance</a>
      </div>
    </div>
  </div>
{% endblock %}

tmfeedback/meetings/templates/meetings/meeting_list.html
{% extends 'base.html' %}

{% block title %}
    Meetings - {{club.name}}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'clubs:home' club.id %}">{{club.name}}</a></li>
    <li class="breadcrumb-item active">All Meetings</li>
{% endblock %}

{% block content %}
    <div class="mb-4">
        <a href="{% url 'clubs:create_meeting' club.id %}" class="btn btn-primary">New Meeting</a>
    </div>

    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>Date</th>
                <th>Theme</th>
                <th>Evaluations</th>
            </tr>
        </thead>
        <tbody>
            {% for meeting in meetings %}
                <tr>
                    <td class="align-middle">{{ meeting.date }}</td>
                    <td class="align-middle"><a href="{% url 'meetings:detail' meeting.pk %}">{{ meeting.theme }}</a></td>
                    <td class="align-middle"><p class="text_muted">Thirteen</p></td>
                    <td class="align-middle"><a href="#">Edit</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
        <nav aria-label="Meetings pagination" class="mb-4">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">Previous</span>
                    </li>
                {% endif %}

                {% for page_num in paginator.page_range %}
                    {% if page_obj.number == page_num %}
                        <li class="page-item active">
                            <span class="page-link">
                                {{ page_num }}
                                <span class="sr-only">(current)</span>
                            </span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">Next</span>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}

{% endblock %}

tmfeedback/meetings/templates/meetings/performance_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  {{performance.get_role_label}}: {{performance.performer.get_full_name}}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'clubs:home' club.id %}">{{club.name}}</a></li>
  <li class="breadcrumb-item"><a href="{% url 'meetings:detail' meeting.pk %}">{{meeting}}</a></li>
  <li class="breadcrumb-item active">
    {{performance.get_role_label}}: {{performance.performer.get_full_name}}
  </li>
{% endblock %}

{% block content %}

  <div class="row">
    <div class="card" style="margin-top:25px">
      <h3 class="card-header text-white bg-dark">Performance</h3>
      <div class="card-body">
        <p>Member: {{performance.performer.get_full_name}}</p>
        <p>Role: {{performance.get_role_label}}</p>
        <p class="text-muted">Title: Not Implemented yet.</p>
        <a href="{% url 'performances:create_eval' performance.pk%}"
           class="btn btn-primary" style="margin-top:10px">
          Evaluate
        </a>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="card" style="margin-top:25px">
      <h4 class="card-header text-white bg-dark">Evaluations</h4>
      <ul class="list-group list-group-flush">
        {% for eval in evaluations %}
          <li class="list-group-item">
            <p>Evaluator: {{ eval.evaluator.get_full_name }}
              <a href="#" class="btn btn-primary" style="margin-left:300px">Edit</a>
              <a href="#" style="margin-left:25px">See full evaluation</a>
            </p>
            {% for category, comment in eval.get_general_comments %}
              <div>{{ category }}: {{ comment }}</div>
            {% endfor %}
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>

{% endblock %}

tmfeedback/meetings/templates/meetings/simple_meeting_index.html
{% extends 'base.html' %}

{% block title %}
    Meetings - {{club.name}}
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'club_index' %}">Clubs</a></li>
    <li class="breadcrumb-item"><a href="{% url 'club_home' club.id %}">{{club.name}} - {{club.id}}</a></li>
    <li class="breadcrumb-item active">Meetings</li>
{% endblock %}

{% block content %}
    <table class="table">
        <thead class="thead-inverse">
            <tr>
                <th>Date</th>
                <th>Theme</th>
                <th>Evaluations</th>
            </tr>
        </thead>
        <tbody>
            {% for meeting in meetings %}
                <tr>
                    <td class="align-middle">{{ meeting.date }}</td>
                    <td class="align-middle">{{ meeting.theme }}</td>
                    <td class="align-middle"><p class="text_muted">Thirteen</p></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
        <nav aria-label="Meetings pagination" class="mb-4">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">Previous</span>
                    </li>
                {% endif %}

                {% for page_num in paginator.page_range %}
                    {% if page_obj.number == page_num %}
                        <li class="page-item active">
                            <span class="page-link">
                                {{ page_num }}
                                <span class="sr-only">(current)</span>
                            </span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <span class="page-link">Next</span>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}

{% endblock %}