tmfeedback/clubs/urls.py
from django.urls import path, include

from . import views
from meetings import views as meet_views

meet_urlpatterns = [
    path('', meet_views.MeetingListView.as_view(), name='meeting_index'),
    path('create/', meet_views.MeetingCreateView.as_view(), name='create_meeting'),
]

app_name = 'clubs'
urlpatterns = [
    path('', views.ClubIndexView.as_view(), name='index'),
    path('create/', views.ClubCreateView.as_view(), name='create'),
    path('<int:club_id>/', views.ClubHomeView.as_view(), name='home'),
    path('<int:club_id>/roster/', views.ClubMemberRoster.as_view(), name='member_roster'),
    path('<int:club_id>/membership_requests/', views.ClubManageRequestsView.as_view(), name='membership_requests'),
    path('<int:club_id>/meetings/', include(meet_urlpatterns))
]

tmfeedback/tmfeedback/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from homepage import views
from users import views as users_views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    path('signup/', users_views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('about/', views.about, name='about'),
    path('boards/', include('boards.urls')),
    path('clubs/', include('clubs.urls', namespace='clubs')),
    path('meetings/', include('meetings.urls.meetings', namespace='meetings')),
    path('performances/', include('meetings.urls.performances', namespace='performances')),
    path('evals/', include('evaluations.urls', namespace='evals')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

tmfeedback/clubs/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from datetime import date as dt_date
from datetime import timedelta


class Club(models.Model):
    name = models.CharField(max_length=100, unique=True)
    id = models.PositiveIntegerField(default=0, primary_key=True)
    description = models.TextField(max_length=1500, default='')
    members = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='clubs')
    member_count = models.PositiveIntegerField(default=1)
    organizer = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='organizing',
                                  null=True, on_delete=models.SET_NULL)
    membership_requests = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='pending_clubs')

    def __str__(self):
        return self.name

    def has_member(self, user):
        return self.members.filter(pk=user.pk).exists()

    def has_pending_member(self, user):
        return self.membership_requests.filter(pk=user.pk).exists()

    def add_member(self, user):
        if not user.is_authenticated:
            raise RuntimeError('Attempting to add an unauthenticated User as a club member.')

        self.members.add(user)
        self.member_count += 1
        return

    def get_absolute_url(self):
        kwargs = {'club_id': self.id}
        return reverse('club_home', kwargs=kwargs)

    def get_meetings_in(self, month: int, year: int):
        """
        Return all the meetings of this club that have occurred in the specified month and year.

        :param month: Integer value between 1 and 12. January (1) .... December (12)
        :param year: Integer value including the millennium and century. Ex: 2018
        :return: Django Queryset of the list of Meetings.
        """
        month_str = str(month)
        year_str = str(year)
        meeting_query_set = self.meetings.filter(date__month=month_str, date__year=year_str)
        meeting_query_set = meeting_query_set.order_by('-date')
        return meeting_query_set

    def get_meetings_from_last_n_weeks(self, n: int, date=None):
        """
        Return all meetings of this club that have occurred in the last N weeks, including the current week.

        :param n: Positive non-zero integer.
        :param date: Date object from datetime. Leave blank if you want to use today's date.
        :return: Django Queryset of the list of Meetings.
        """
        if date is None:
            date = dt_date.today()

        n_weeks_delta = timedelta(weeks=n)
        start_date = date - n_weeks_delta

        start_date_str = dt_date.strftime(start_date, "%Y-%m-%d")
        end_date_str = dt_date.strftime(date, "%Y-%m-%d")
        meeting_query_set = self.meetings.filter(date__range=[start_date_str, end_date_str])
        meeting_query_set = meeting_query_set.order_by('-date')
        return meeting_query_set

    def get_roster(self):
        """
        Get the list of members in a club.

        :return: Django Queryset of the members in a club.
        """
        members = self.members.order_by('last_name')
        return members

tmfeedback/clubs/forms.py
from django import forms

from .models import Club


class MembershipRequestForm(forms.Form):
    pass


class MembershipApprovalForm(forms.Form):
    CHOICES = [('Y', 'Approve'), ('N', 'Deny')]
    request_decision = forms.ChoiceField(choices=CHOICES, widget=forms.RadioSelect)


def create_membership_request_formset(form_count):
    return forms.formset_factory(MembershipApprovalForm, extra=form_count)


class ClubModelForm(forms.ModelForm):
    class Meta:
        model = Club
        fields = ['name', 'id', 'description']

tmfeedback/clubs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, View, FormView, DetailView, TemplateView
from django.views.generic.list import MultipleObjectMixin
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.forms import formset_factory
import sys
from datetime import date

from .models import Club
from .forms import MembershipRequestForm, MembershipApprovalForm, create_membership_request_formset, ClubModelForm


class ClubOrganizerRequiredMixin(UserPassesTestMixin):
    """ Mixin that enforces the request's user be the organizer for a particular club.
    This mixin assumes that:
        1) kwargs is a member variable of self
        2) the key 'club_id' exists in kwargs
        3) request is a member variable of self
    Should always be used after LoginRequiredMixin.
    """
    def test_func(self):
        club = self.get_club()
        user = self.request.user
        return Club.objects.filter(id=club.id, organizer=user).exists()

    def get_club(self):
        return get_object_or_404(Club, pk=self.kwargs['club_id'])


class ClubMembershipRequiredMixin(UserPassesTestMixin):
    """ Mixin that enforces the request's user be the organizer for a particular club.
    This mixin assumes that:
        1) kwargs is a member variable of self
        2) the key 'club_id' exists in kwargs
        3) request is a member variable of self
    Should always be used after LoginRequiredMixin.

    Can override get_club method to use this mixin for views that do not have 'club_id'
    in its kwargs. Allows extendability for any circumstance in which a club can be found.
    """
    def test_func(self):
        club = self.get_club()
        user = self.request.user
        return club.has_member(user)

    def get_club(self):
        return get_object_or_404(Club, pk=self.kwargs['club_id'])


class ClubIndexView(ListView):
    model = Club
    context_object_name = 'clubs'
    template_name = 'clubs/club_index.html'


class ClubHomeView(View):
    @staticmethod
    def get(request, club_id):
        club = get_object_or_404(Club, pk=club_id)
        user = request.user
        context = {
            'club': club,
            'meetings': club.get_meetings_from_last_n_weeks(6),
            'members': club.get_roster()
        }
        if user.is_authenticated:
            context['is_member'] = club.has_member(user)
            context['has_pending_membership'] = club.has_pending_member(user)
        else:
            context['is_member'] = False
            context['is_member'] = False

        return render(request, 'clubs/club_home.html', context)

    def post(self, request, club_id):
        form = MembershipRequestForm(request.POST)
        if form.is_valid():
            user = request.user
            club = get_object_or_404(Club, pk=club_id)
            club.membership_requests.add(user)
            club.save()
            return redirect('clubs:home', club_id=club_id)
        else:
            return redirect('clubs:index')


class ClubCreateView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        view = ClubCreationDisplay.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = ClubCreationSubmission.as_view()
        return view(request, *args, **kwargs)


class ClubCreationDisplay(TemplateView):
    template_name = 'clubs/club_create.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ClubModelForm()
        return context


class ClubCreationSubmission(TemplateView):
    template_name = 'clubs/club_create.html'

    def post(self, request):
        form = ClubModelForm(request.POST)
        if form.is_valid():
            new_club = form.save(commit=False)
            new_club.organizer = request.user
            new_club.save()
            new_club.add_member(request.user)
            return redirect('clubs:home', club_id=new_club.id)
        else:
            return render(request, 'clubs/club_create.html', {'form': form})


class ClubMemberRoster(LoginRequiredMixin, ListView):
    login_url = '/login/'
    model = get_user_model()
    context_object_name = 'members'
    template_name = 'clubs/club_member_roster.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        kwargs['club'] = self.club
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.club = get_object_or_404(Club, id=self.kwargs.get('club_id'))
        queryset = self.club.members.order_by('-last_name')
        return queryset


class ClubManageRequestsView(LoginRequiredMixin, ClubOrganizerRequiredMixin, View):

    def get(self, request, club_id):
        club = get_object_or_404(Club, pk=club_id)
        requesters = get_user_model().objects.filter(pending_clubs__pk=club_id)
        requesters = requesters.order_by('first_name')
        formset = create_membership_request_formset(requesters.count())()

        request_forms = zip(formset, requesters)
        context = {'form_requests': request_forms,
                   'club': club,
                   'formset': formset,
                   'request_count': requesters.count()
                   }
        return render(request, 'clubs/club_membership_requests.html', context)

    def post(self, request, club_id):
        club = get_object_or_404(Club, pk=club_id)
        requesters = get_user_model().objects.filter(pending_clubs__pk=club_id)
        requesters = requesters.order_by('first_name')
        formset = create_membership_request_formset(requesters.count())(request.POST)

        for form, user in zip(formset, requesters):
            if form.is_valid():
                data = form.cleaned_data
                self.fulfill_membership_decision(data, user, club)

        return redirect('clubs:member_roster', club_id=club_id)

    @staticmethod
    def fulfill_membership_decision(form_data, user, club):
        response_key = 'request_decision'
        if response_key in form_data.keys():
            if form_data[response_key] == 'Y':
                club.membership_requests.remove(user)
                club.members.add(user)
                club.save()
            else:
                club.membership_requests.remove(user)
                club.save()
        return


# class ClubMembershipRequestDisplay(LoginRequiredMixin, ClubOrganizerPermissionRequiredMixin, DetailView):
#     model = Club
#     pk_url_kwarg = 'club_id'
#     context_object_name = 'club'
#     template_name = 'clubs/club_membership_requests.html'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#
#         requesters = self.object.membership_requests.all()
#         requesters = requesters.order_by('first_name')
#         formset = create_membership_request_formset(requesters.count())()
#
#         context['formset'] = formset
#         context['form_requests'] = zip(formset, requesters)
#
#         return context
#
#
# class ClubMembershipRequestApproval(LoginRequiredMixin,
#         ClubOrganizerPermissionRequiredMixin, SingleObjectMixin, FormView):
#     form_class = create_membership_request_formset(1)
#     model = Club
#     pk_url_kwarg = 'club_id'
#     context_object_name = 'club'
#     template_name = 'clubs/club_membership_requests.html'
#
#     def post(self, request, *args, **kwargs):
#
#
#         return super().post(request, *args, **kwargs)
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#
#         requesters = self.object.membership_requests.all()
#         requesters = requesters.order_by('first_name')
#         formset = create_membership_request_formset(requesters.count())(self.request.POST)
#
#         context['formset'] = formset
#         context['form_requests'] = zip(formset, requesters)
#
#         return context
#
#     def get_success_url(self):
#
# class ClubManageMembershipRequests(LoginRequiredMixin, View):
#
#     def get(self, request, *args, **kwargs):
#         view = ClubMembershipRequestDisplay.as_view()
#         return view(request, *args, **kwargs)
#
#     def post(self, request, *args, **kwargs):
#         view = ClubMembershipRequestApproval.as_view()
#         return view(request, *args, **kwargs)

tmfeedback/clubs/templates/clubs/club_create.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}
  Start a New Club
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'clubs:index' %}">Clubs</a></li>
  <li class="breadcrumb-item active">New Club</li>
{% endblock %}

{% block content %}
  <form method="post" novalidate>
    {% csrf_token %}
    {% include 'includes/form.html' %}
    <button type="submit" class="btn btn-success">Create</button>
  </form>
{% endblock %}

tmfeedback/clubs/templates/clubs/club_home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{club.name}}
{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'clubs:index' %}">Clubs</a></li>
  <li class="breadcrumb-item active">{{club.name}}</li>
{% endblock %}

{% block content %}

    <div class="row">
        <div class="card mb-3">
            <img class="card-img-top" src="{% static 'img/tm_red_banner.png' %}" alt="card club banner image">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-8">
                        <h2 class="card-title">{{club.name}}</h2>
                        <h6 class="card-subtitle mb-2 text-muted">Club: {{club.id}}</h6>
                    </div>
                    <div class="col-md-4">
                        {% if user.is_authenticated %}
                            {% if is_member %}
                                <button type="button" class="btn btn-success float-right" disabled>Member</button>
                            {% elif has_pending_membership %}
                                <button type="button" class="btn btn-info float-right" disabled>Pending Approval</button>
                            {% else %}
                                <form action="{% url 'clubs:home' club.id %}" method="post" class="form-inline ml-auto">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-primary float-right">Request Membership</button>
                                </form>
                            {% endif %}
                        {% else %}
                            <button type="button" class="btn btn-primary" disabled>Login to Join</button>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card" style="margin-top:35px;">
        <div class="card-body">
            <p>Preset Message: Welcome to the {{club.name}} evaluation homepage. Here, you'll find and give constructive
                feedback to your fellow club members.</p>
            <p>User Defined Message: {{club.description}}</p>
        </div>
    </div>
    <div class="card w-75 text-center" style="margin:auto; margin-top:25px">
        <h4 class="card-header text-white bg-dark">Evaluation Quotes</h4>
        <div class="card-body">
            This is where quote stuff goes.
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="card" style="margin-top:25px">
                <h4 class="card-header text-white bg-dark">Club Meetings</h4>
                <table class="table">
                    <thead class="thead-inverse">
                        <tr>
                            <th>Meeting</th>
                            <th>Evaluations</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for meeting in meetings %}
                            <tr>
                                <td class="align-middle"><a href="{% url 'meetings:detail' meeting.pk %}">{{ meeting }}</a></td>
                                <td class="align-middle"><p class="text_muted">0</p></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="card-footer">
                    <p><a href="{% url 'clubs:meeting_index' club.id %}">Go to all meetings</a> or
                        <a href="{% url 'clubs:create_meeting' club.id %}">Create a new meeting</a></p>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card" style="margin-top:25px">
                <h4 class="card-header text-white bg-dark">Members</h4>
                <table class="table">
                    <thead class="thead-inverse">
                        <tr>
                            <th>Member</th>
                            <th>Performances</th>
                            <th>Evaluations</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for member in members %}
                            <tr>
                                <td class="align-middle"><a href="#">{{ member.get_full_name }}</a></td>
                                <td class="align-middle"><p class="text_muted">0</p></td>
                                <td class="align-middle"><p class="text_muted">0</p></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <div class="card-footer">
                    <p><a href="{% url 'clubs:member_roster' club.id %}">See full roster</a></p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="card" style="margin-top:25px">
                <h4 class="card-header text-white bg-dark">Participation Leaderboard</h4>
                <div class="card-body">
                    <p>Work in Progress.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card" style="margin-top:25px">
                <h4 class="card-header text-white bg-dark">Contact</h4>
                <div class="card-body">
                    <p>Organizer: {{club.organizer.get_full_name}}</p>
                    <p>Email: {{club.organizer.email}}</p>
                </div>
            </div>
        </div>

    </div>
{% endblock %}

tmfeedback/clubs/templates/clubs/club_index.html
{% extends 'base.html' %}

{% block breadcrumb %}
  <li class="breadcrumb-item active">Clubs</li>
{% endblock %}

{% block content %}
  <div class="row row-no-gutters">
    <div class="col-md-2"><p>Don't see your club?</p></div>
    <div class="col-md-1">
      <a href="{% url 'clubs:create' %}" class="btn btn-primary">Register Here</a>
    </div>
  </div>

  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Club Name</th>
        <th>Club ID</th>
        <th>Registered Members</th>
        <th>Organizer</th>
      </tr>
    </thead>
    <tbody>
      {% for club in clubs %}
        <tr>
          <td>
            <a href="{% url 'clubs:home' club.pk %}">{{ club.name }}</a>
          </td>
          <td class="align-middle">{{ club.pk }}</td>
          <td class="align-middle">{{ club.member_count }}</td>
          <td class="align-middle">{{ club.organizer.get_full_name }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

tmfeedback/clubs/templates/clubs/club_manage_requests.html
{% extends 'base.html' %}

{% block title %}
  {{ club.name }} - Manage Membership Requests
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'club_index' %}">Clubs</a></li>
    <li class="breadcrumb-item"><a href="{% url 'club_home' club.id %}">{{club.name}} - {{club.id}}</a></li>
    <li class="breadcrumb-item active">Membership Requests</li>
{% endblock %}

{% block content %}
    {% if request_count > 0 %}
        <form method="post" novalidate>
            {% csrf_token %}
            {{ formset.management_form }}
            <table class="table mb-4">
                <thead class="thead-inverse">
                    <tr>
                        <th>User</th>
                        <th>Email</th>
                        <th>Club ID</th>
                        <th>Decision</th>
                    </tr>
                </thead>
                <tbody>
                    {% for form, user in form_requests %}
                        <tr>
                            <td><a href="#">{{ user.get_full_name }}</a></td>
                            <td>{{ user.email }}</td>
                            <td>{{ club.id }}</td>
                            <td>
                                {% for radio in form.request_decision %}
                                    <div class="my_radio">
                                        {{ radio }}
                                    </div>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <button type="submit" class="btn btn-success">Submit Updates</button>
        </form>
    {% else %}
        <p>There are no requests to approve.</p>
    {% endif %}
{% endblock %}

tmfeedback/clubs/templates/clubs/club_member_roster.html
{% extends 'base.html' %}

{% block title %}
  {{ club.name }} - Roster
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'clubs:home' club.id %}">{{club.name}}</a></li>
    <li class="breadcrumb-item active">Member Roster</li>
{% endblock %}

{% block content %}
    <table class="table mb-4">
        <thead class="thead-inverse">
            <tr>
                <th>Member</th>
                <th>Email</th>
                <th>Titles</th>
                <th>Evaluations</th>
                <th>Last Post</th>
            </tr>
        </thead>
        <tbody>
            {% for member in members %}
                <tr>
                    <td><a href="#">{{ member.get_full_name }}</a></td>
                    <td>{{ member.email }}</td>
                    <td><p class="text_muted">CC, CL</p></td>
                    <td><p class="text_muted">Zero</p></td>
                    <td><p class="text_muted">Not built yet</p></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

  {% if is_paginated %}
    <nav aria-label="Topics pagination" class="mb-4">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <span class="page-link">Previous</span>
          </li>
        {% endif %}

        {% for page_num in paginator.page_range %}
          {% if page_obj.number == page_num %}
            <li class="page-item active">
              <span class="page-link">
                {{ page_num }}
                <span class="sr-only">(current)</span>
              </span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
            </li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <span class="page-link">Next</span>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}

{% endblock %}

tmfeedback/clubs/templates/clubs/club_membership_requests.html
{% extends 'base.html' %}

{% block title %}
  {{ club.name }} - Manage Membership Requests
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'clubs:home' club.id %}">{{club.name}}</a></li>
    <li class="breadcrumb-item active">Membership Requests</li>
{% endblock %}

{% block content %}
    {% if request_count > 0 %}
        <form method="post" novalidate>
            {% csrf_token %}
            {{ formset.management_form }}
            <table class="table mb-4">
                <thead class="thead-inverse">
                    <tr>
                        <th>User</th>
                        <th>Email</th>
                        <th>Club ID</th>
                        <th>Decision</th>
                    </tr>
                </thead>
                <tbody>
                    {% for form, user in form_requests %}
                        <tr>
                            <td><a href="#">{{ user.get_full_name }}</a></td>
                            <td>{{ user.email }}</td>
                            <td>{{ club.id }}</td>
                            <td>
                                {% for radio in form.request_decision %}
                                    <div class="my_radio">
                                        {{ radio }}
                                    </div>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

            <button type="submit" class="btn btn-success">Submit Updates</button>
        </form>
    {% else %}
        <p>There are no requests to approve.</p>
    {% endif %}
{% endblock %}